Fix owyl usage; argument is required.
Fixes this bug:

Traceback (most recent call last):
  File
"/eva_behavior/src/general_behavior.py",
line 696, in <module>
    tree = Tree()
  File
"/eva_behavior/src/general_behavior.py",
line 18, in __init__
    self.blackboard = blackboard.Blackboard()
TypeError: __init__() takes exactly 2 arguments (1 given)